import { NextRequest, NextResponse } from "next/server";
import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import Groq from "groq-sdk";

const groq = new Groq({
  apiKey: process.env.GROQ_API_KEY,
});

export async function POST(req: NextRequest) {
  try {
    // 1. SECURITY FIX: Validate Supabase session before accepting any GitHub operations
    const authHeader = req.headers.get("Authorization");
    if (!authHeader || !authHeader.startsWith("Bearer ")) {
      return NextResponse.json(
        { error: "Unauthorized. Missing authentication token." },
        { status: 401 },
      );
    }

    const supabaseToken = authHeader.split(" ")[1];
    const cookieStore = await cookies();

    const supabase = createServerClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
      {
        cookies: {
          getAll() {
            return cookieStore.getAll();
          },
          setAll() {},
        },
        global: { headers: { Authorization: `Bearer ${supabaseToken}` } },
      },
    );

    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser();
    if (authError || !user) {
      return NextResponse.json(
        { error: "Unauthorized. Invalid session." },
        { status: 401 },
      );
    }

    // 2. Parse request and resolve GitHub token
    const {
      repoName,
      files,
      token: bodyToken,
      isPrivate = true,
      recentPrompt,
      commitMessage: manualCommitMessage,
    } = await req.json();

    const {
      data: { session },
    } = await supabase.auth.getSession();

    const githubToken =
      bodyToken ||
      session?.provider_token ||
      session?.user?.user_metadata?.github_token;

    if (!repoName || !files || !githubToken) {
      return NextResponse.json(
        {
          error: !githubToken
            ? "No GitHub connection found. Please sign in with GitHub or provide a Personal Access Token."
            : "Missing required parameters (repoName or files).",
        },
        { status: 400 },
      );
    }

    const headers = {
      Authorization: `Bearer ${githubToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    };

    // 3. Get authenticated GitHub user
    const userRes = await fetch("https://api.github.com/user", { headers });
    if (!userRes.ok) {
      throw new Error(
        "Invalid or expired GitHub token. Try re-authenticating with GitHub.",
      );
    }
    const githubUser = await userRes.json();
    const owner = githubUser.login;

    // 4. Create or verify the repository (422 means it exists, which is fine)
    const repoRes = await fetch("https://api.github.com/user/repos", {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: repoName,
        description: "Generated by Archeon Visual Architecture Studio",
        private: isPrivate,
        auto_init: true,
      }),
    });

    if (!repoRes.ok && repoRes.status !== 422) {
      const err = await repoRes.json();
      throw new Error(`Failed to create repository: ${err.message}`);
    }

    if (repoRes.status === 201) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    // 5. EDGE CASE FIX: Handle Empty Repositories
    let branchName = "main";
    let baseCommitSha: string | null = null;
    let baseTreeSha: string | null = null;
    let isNewOrEmptyRepo = false;

    let refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`,
      { headers },
    );

    if (!refRes.ok) {
      refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/master`,
        { headers },
      );
      if (refRes.ok) branchName = "master";
    }

    if (refRes.ok) {
      const refData = await refRes.json();
      baseCommitSha = refData.object.sha;

      const baseCommitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/commits/${baseCommitSha}`,
        { headers },
      );
      const baseCommitData = await baseCommitRes.json();
      baseTreeSha = baseCommitData.tree.sha;
    } else {
      isNewOrEmptyRepo = true; // Repo exists but has no commits/branches yet
    }

    // 6. Create Blobs in parallel
    const blobPromises = Object.entries(files).map(async ([path, content]) => {
      const cleanPath = path.startsWith("/") ? path.substring(1) : path;
      const blobRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/blobs`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            content: content as string,
            encoding: "utf-8",
          }),
        },
      );
      const blobData = await blobRes.json();
      return {
        path: cleanPath,
        mode: "100644",
        type: "blob",
        sha: blobData.sha,
      };
    });

    const treeDataPayload = await Promise.all(blobPromises);

    // 7. Create a new Tree (conditionally attach base_tree if it exists)
    const treePayload: any = { tree: treeDataPayload };
    if (baseTreeSha) treePayload.base_tree = baseTreeSha;

    const treeRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/trees`,
      {
        method: "POST",
        headers,
        body: JSON.stringify(treePayload),
      },
    );
    const treeData = await treeRes.json();

    // 8. Resolve Final Commit Message
    let finalCommitMessage = manualCommitMessage?.trim();

    if (!finalCommitMessage && recentPrompt && process.env.GROQ_API_KEY) {
      try {
        const completion = await groq.chat.completions.create({
          model: "openai/gpt-oss-120b",
          messages: [
            {
              role: "system",
              content:
                "You are a Git bot. Convert the user request into a single, concise Conventional Commit message. Output ONLY the raw commit message string. Do not use quotes or markdown.",
            },
            {
              role: "user",
              content: recentPrompt,
            },
          ],
          stream: false,
        });

        return completion.choices[0]?.message?.content?.trim() || "";
      } catch (e) {
        console.warn(
          "AI commit generation failed, falling back to default.",
          e,
        );
      }
    }

    if (!finalCommitMessage) {
      finalCommitMessage =
        repoRes.status === 201 || isNewOrEmptyRepo
          ? "feat: initial architecture generation"
          : "feat: architecture update";
    }

    // 9. Create the Commit (conditionally attach parent if it exists)
    const commitPayload: any = {
      message: finalCommitMessage,
      tree: treeData.sha,
    };
    if (baseCommitSha) commitPayload.parents = [baseCommitSha];

    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/commits`,
      {
        method: "POST",
        headers,
        body: JSON.stringify(commitPayload),
      },
    );
    const commitData = await commitRes.json();

    // 10. Update or Create the Branch Reference
    if (isNewOrEmptyRepo) {
      // POST to create the initial branch reference
      await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            ref: `refs/heads/${branchName}`,
            sha: commitData.sha,
          }),
        },
      );
    } else {
      // PATCH to update the existing branch reference
      await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/${branchName}`,
        {
          method: "PATCH",
          headers,
          body: JSON.stringify({
            sha: commitData.sha,
            force: true,
          }),
        },
      );
    }

    return NextResponse.json({
      success: true,
      url: `https://github.com/${owner}/${repoName}`,
      commitMessage: finalCommitMessage,
    });
  } catch (error: any) {
    console.error("GitHub Export Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
