import { NextRequest, NextResponse } from 'next/server';
import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';

export async function POST(req: NextRequest) {
  try {
    const {
      repoName,
      files,
      token: bodyToken,
      isPrivate = true,
      recentPrompt,
      commitMessage: manualCommitMessage,
    } = await req.json();

    // 1. Resolve token: use explicit bodyToken if provided, otherwise read from Supabase GitHub OAuth session
    let token = bodyToken;

    if (!token) {
      const cookieStore = await cookies();
      const supabase = createServerClient(
        process.env.NEXT_PUBLIC_SUPABASE_URL!,
        process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!,
        {
          cookies: {
            getAll() {
              return cookieStore.getAll();
            },
            setAll() {},
          },
        }
      );

      const {
        data: { session },
      } = await supabase.auth.getSession();

      token =
        session?.provider_token ||
        session?.user?.user_metadata?.github_token ||
        null;
    }

    if (!repoName || !files || !token) {
      return NextResponse.json(
        {
          error: !token
            ? 'No GitHub connection found. Please sign in with GitHub or provide a Personal Access Token.'
            : 'Missing required parameters (repoName or files).',
        },
        { status: 400 }
      );
    }

    const headers = {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };

    // 2. Get authenticated GitHub user
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) {
      throw new Error(
        'Invalid or expired GitHub token. Try re-authenticating with GitHub.'
      );
    }
    const user = await userRes.json();
    const owner = user.login;

    // 3. Create the repository (422 means it already exists, so we commit to the existing repo)
    const repoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: repoName,
        description: 'Generated by Archeon Visual Architecture Studio',
        private: isPrivate,
        auto_init: true,
      }),
    });

    if (!repoRes.ok && repoRes.status !== 422) {
      const err = await repoRes.json();
      throw new Error(`Failed to create repository: ${err.message}`);
    }

    if (repoRes.status === 201) {
      await new Promise((resolve) => setTimeout(resolve, 1000));
    }

    // 4. Get reference to main (or master) branch
    let branchName = 'main';
    let refRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`,
      { headers }
    );
    if (!refRes.ok) {
      branchName = 'master';
      refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/master`,
        { headers }
      );
    }
    if (!refRes.ok) {
      throw new Error(
        'Could not fetch main branch reference. Ensure the repository is initialized.'
      );
    }

    const refData = await refRes.json();
    const baseCommitSha = refData.object.sha;

    const baseCommitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/commits/${baseCommitSha}`,
      { headers }
    );
    const baseCommitData = await baseCommitRes.json();
    const baseTreeSha = baseCommitData.tree.sha;

    // 5. Create Blobs in parallel
    const blobPromises = Object.entries(files).map(async ([path, content]) => {
      const cleanPath = path.startsWith('/') ? path.substring(1) : path;

      const blobRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/blobs`,
        {
          method: 'POST',
          headers,
          body: JSON.stringify({
            content: content as string,
            encoding: 'utf-8',
          }),
        }
      );
      const blobData = await blobRes.json();

      return {
        path: cleanPath,
        mode: '100644',
        type: 'blob',
        sha: blobData.sha,
      };
    });

    const treeDataPayload = await Promise.all(blobPromises);

    // 6. Create a new Tree
    const treeRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/trees`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          base_tree: baseTreeSha,
          tree: treeDataPayload,
        }),
      }
    );
    const treeData = await treeRes.json();

    // 6.5 Resolve Final Commit Message (Manual -> Groq AI -> Default)
    let finalCommitMessage = manualCommitMessage?.trim();

    if (!finalCommitMessage && recentPrompt && process.env.GROQ_API_KEY) {
      try {
        const aiRes = await fetch(
          'https://api.groq.com/openai/v1/chat/completions',
          {
            method: 'POST',
            headers: {
              Authorization: `Bearer ${process.env.GROQ_API_KEY}`,
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({
              model: 'llama-3.1-8b-instant',
              messages: [
                {
                  role: 'system',
                  content:
                    'You are a Git bot. Convert the user request into a single, concise Conventional Commit message (e.g., "feat: add user auth" or "fix: relation cardinality"). Output ONLY the raw commit message string. Do not use quotes or markdown.',
                },
                { role: 'user', content: recentPrompt },
              ],
              temperature: 0.2,
            }),
          }
        );

        if (aiRes.ok) {
          const aiData = await aiRes.json();
          const aiMessage = aiData.choices?.[0]?.message?.content?.trim();
          if (aiMessage) finalCommitMessage = aiMessage;
        }
      } catch (e) {
        console.warn('AI commit generation failed, falling back to default.', e);
      }
    }

    if (!finalCommitMessage) {
      finalCommitMessage =
        repoRes.status === 201
          ? 'feat: initial architecture generation'
          : 'feat: architecture update';
    }

    // 7. Create the Commit
    const commitRes = await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/commits`,
      {
        method: 'POST',
        headers,
        body: JSON.stringify({
          message: finalCommitMessage,
          tree: treeData.sha,
          parents: [baseCommitSha],
        }),
      }
    );
    const commitData = await commitRes.json();

    // 8. Update the Branch Reference
    await fetch(
      `https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/${branchName}`,
      {
        method: 'PATCH',
        headers,
        body: JSON.stringify({
          sha: commitData.sha,
          force: true,
        }),
      }
    );

    return NextResponse.json({
      success: true,
      url: `https://github.com/${owner}/${repoName}`,
      commitMessage: finalCommitMessage,
    });
  } catch (error: any) {
    console.error('GitHub Export Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}