import { NextRequest, NextResponse } from 'next/server';

export async function POST(req: NextRequest) {
  try {
    // 1. Extract the manual commit message from the frontend payload
    const { repoName, files, token, recentPrompt, commitMessage: manualCommitMessage } = await req.json();

    if (!repoName || !files || !token) {
      return NextResponse.json({ error: 'Missing required parameters' }, { status: 400 });
    }

    const headers = {
      'Authorization': `Bearer ${token}`,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    };

    // 1. Get authenticated user
    const userRes = await fetch('https://api.github.com/user', { headers });
    if (!userRes.ok) throw new Error('Invalid GitHub token');
    const user = await userRes.json();
    const owner = user.login;

    // 2. Create the repository
    const repoRes = await fetch('https://api.github.com/user/repos', {
      method: 'POST',
      headers,
      body: JSON.stringify({
        name: repoName,
        description: 'Generated by Zero-Dollar Architecture IDE',
        private: true,
        auto_init: true, // Creates the initial commit needed for the branch reference
      }),
    });
    
    if (!repoRes.ok && repoRes.status !== 422) {
      const err = await repoRes.json();
      throw new Error(`Failed to create repository: ${err.message}`);
    }

    // Wait briefly if the repo was just created to ensure the auto-init commit is available
    if (repoRes.status === 201) {
      await new Promise(resolve => setTimeout(resolve, 1000));
    }

    // 3. Get the reference to the main branch
    const refRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`, { headers });
    if (!refRes.ok) {
        throw new Error('Could not fetch main branch reference. Ensure the repository is initialized.');
    }
    const refData = await refRes.json();
    const baseCommitSha = refData.object.sha;

    // FIX: Fetch the actual commit to get its exact tree SHA (best practice for base_tree)
    const baseCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits/${baseCommitSha}`, { headers });
    const baseCommitData = await baseCommitRes.json();
    const baseTreeSha = baseCommitData.tree.sha;

    // 4. Create Blobs in parallel (The contents of our virtual files)
    const blobPromises = Object.entries(files).map(async ([path, content]) => {
      // Remove leading slash if present
      const cleanPath = path.startsWith('/') ? path.substring(1) : path;
      
      const blobRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/blobs`, {
        method: 'POST',
        headers,
        body: JSON.stringify({
          content: content as string,
          encoding: 'utf-8',
        }),
      });
      const blobData = await blobRes.json();
      
      return {
        path: cleanPath,
        mode: '100644', // Standard file mode
        type: 'blob',
        sha: blobData.sha,
      };
    });

    const treeDataPayload = await Promise.all(blobPromises);

    // 5. Create a new Tree
    const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/trees`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeDataPayload,
      }),
    });
    const treeData = await treeRes.json();

    // 5.5 Resolve the Final Commit Message
    let finalCommitMessage = manualCommitMessage;
    
    // Fallback to Groq AI generation if no manual override was provided in the UI
    if (!finalCommitMessage && recentPrompt) {
      try {
        const aiRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${process.env.GROQ_API_KEY}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            model: 'llama-3.1-8b-instant',
            messages: [
              { 
                role: 'system', 
                content: 'You are a Git bot. Convert the user request into a single, concise Conventional Commit message (e.g., "feat: add user auth" or "fix: relation cardinality"). Output ONLY the raw commit message string. Do not use quotes or markdown.' 
              },
              { role: 'user', content: recentPrompt }
            ],
            temperature: 0.2,
          }),
        });
        
        if (aiRes.ok) {
          const aiData = await aiRes.json();
          const aiMessage = aiData.choices?.[0]?.message?.content?.trim();
          if (aiMessage) finalCommitMessage = aiMessage;
        } else {
          console.warn("Groq API returned an error:", await aiRes.text());
        }
      } catch (e) {
        console.warn("AI commit generation failed, falling back to default.", e);
      }
    }

    // Ultimate fallback if both manual and AI messages fail
    if (!finalCommitMessage) {
      finalCommitMessage = repoRes.status === 201 
        ? 'feat: initial architecture generation' 
        : 'feat: architecture update';
    }

    // 6. Create the Commit
    const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/commits`, {
      method: 'POST',
      headers,
      body: JSON.stringify({
        message: finalCommitMessage,
        tree: treeData.sha,
        parents: [baseCommitSha],
      }),
    });
    const commitData = await commitRes.json();

    // 7. Update the Branch Reference
    await fetch(`https://api.github.com/repos/${owner}/${repoName}/git/refs/heads/main`, {
      method: 'PATCH',
      headers,
      body: JSON.stringify({
        sha: commitData.sha,
        force: true,
      }),
    });

    return NextResponse.json({ 
      success: true, 
      url: `https://github.com/${owner}/${repoName}` 
    });

  } catch (error: any) {
    console.error('GitHub Export Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}